// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC--qoFQ81wIt7-G9ix2_PdufTLibzlzbk',
    appId: '1:706149916837:web:9b29fcf2884ea5443bed4c',
    messagingSenderId: '706149916837',
    projectId: 'chatterspace-new',
    authDomain: 'chatterspace-new.firebaseapp.com',
    storageBucket: 'chatterspace-new.appspot.com',
    measurementId: 'G-2DEF2C8K53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArSAES7L8a7KtEd24Ime_CVwKOfyOG4kc',
    appId: '1:706149916837:android:0231ea78a40dec363bed4c',
    messagingSenderId: '706149916837',
    projectId: 'chatterspace-new',
    storageBucket: 'chatterspace-new.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6MqWc5HtzI_yyZoO1fHfmPiSbxxFDo7U',
    appId: '1:706149916837:ios:ee4e8a9a1efd99603bed4c',
    messagingSenderId: '706149916837',
    projectId: 'chatterspace-new',
    storageBucket: 'chatterspace-new.appspot.com',
    iosBundleId: 'com.chatterspace.chatterspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6MqWc5HtzI_yyZoO1fHfmPiSbxxFDo7U',
    appId: '1:706149916837:ios:ee4e8a9a1efd99603bed4c',
    messagingSenderId: '706149916837',
    projectId: 'chatterspace-new',
    storageBucket: 'chatterspace-new.appspot.com',
    iosBundleId: 'com.chatterspace.chatterspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC--qoFQ81wIt7-G9ix2_PdufTLibzlzbk',
    appId: '1:706149916837:web:cff6c374bfebdcb73bed4c',
    messagingSenderId: '706149916837',
    projectId: 'chatterspace-new',
    authDomain: 'chatterspace-new.firebaseapp.com',
    storageBucket: 'chatterspace-new.appspot.com',
    measurementId: 'G-67R232MGET',
  );
}
